version: "3.8"

# Before "compose up" this file, cd to the api folder, make sure the database container is running, 
# and then apply the following command to generate the JAR file:
# ./mvnw package

services:
    database:
        image: postgres
        container_name: postgresql_database_movie_recommendations
        hostname: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5434:5432
        volumes:
            - ./database/postgres-volume:/var/lib/postgresql/data
        networks:
            - my-docker-network
    api:
        build:
            context: api
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - database
        restart: always
        networks:
            - my-docker-network
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql_database_movie_recommendations:5432/postgres
volumes:
    postgres-volume:
networks:
    my-docker-network:
