version: "3.8"

services:
    database:
        image: postgres
        container_name: database
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5434:5432
        volumes:
            - ./database/postgres-volume:/var/lib/postgresql/data
volumes:
    postgres-volume:
