version: "3.8"

services:
    database:
        image: postgres
        container_name: postgresql_database_movie_recommendations
        hostname: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5434:5432
        volumes:
            - ./database/postgres-volume:/var/lib/postgresql/data
        networks:
            - my-docker-network
volumes:
    postgres-volume:
networks:
    my-docker-network:
